config/routes.rb
Rails.application.routes.draw do
  devise_for :users, :controllers => { registrations: 'registrations' }
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  resources :pins



  root "pins#index"

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/pin.rb
class Pin < ApplicationRecord
  has_attached_file :image, styles: {
    instagram: "640x640>",
    large: "500x500>",
    medium: "300x300>",
    thumb: "100x100>" }, default_url: "/images/:style/missing.png"
  validates_attachment_content_type :image, content_type: /\Aimage\/.*\z/

  belongs_to :user
  validates :user_id, presence: true
end

app/models/user.rb
class User < ApplicationRecord

  validates :user_name, presence: true, length: { minimum: 4, maximum: 16 }
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  has_many :pins, dependent: :destroy
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/pins_controller.rb
class PinsController < ApplicationController
  before_action :authenticate_user!

  before_action :find_pin, only: [:show ,:edit, :update, :destroy ]

  before_action :owned_post, only: [:edit, :update, :destroy]

  def index
    @pins = Pin.all
  end

  def show
  end

  def new
    @pin = current_user.pins.build
  end

  def create
    @pin = current_user.pins.build(pin_params)

    if @pin.save
      flash[:success] = "Pin Created"
      redirect_to @pin
    else
      flash[:alert] = "Your new post couldn't be created!  Please check the form."
      render 'new'
    end
  end

  def edit

  end

  def update
    if @pin.update(pin_params)
      flash[:success] = "Magically Updated"
      redirect_to @pin
    else
      render 'edit'
    end
  end

  def destroy
    @pin.destroy
    flash[:success] = "It's Gone NOW!"
    redirect_to root_path
  end

  private

  def pin_params
    params.require(:pin).permit(:title, :description, :image)
  end

  def find_pin
    @pin = Pin.find(params[:id])
  end

  def owned_post
    unless current_user == @pin.user
      flash[:alert] = "That post doesn't belong to you!"
      redirect_to root_path
    end
  end

end

app/controllers/registrations_controller.rb
class RegistrationsController < Devise::RegistrationsController

  private

  def sign_up_params
    params.require(:user).permit(:email, :user_name, :password, :password_confirmation)
  end

  def account_update_params
    params.require(:user).permit(:email, :user_name, :password, :password_confirmation, :current_password)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/pins_helper.rb
module PinsHelper
end

app/views/layouts/_nav.html.haml
%nav.navbar.navbar-toggleable-md.navbar-light.bg-faded
  %button.navbar-toggler.navbar-toggler-right{"aria-controls" => "navbar1", "aria-expanded" => "false", "aria-label" => "Toggle navigation", "data-target" => "#navbar1", "data-toggle" => "collapse", :type => "button"}
    %span.navbar-toggler-icon
  .navbar-brand= link_to "Photo Board", root_path
  -# #navbar1.collapse.navbar-collapse.justify-content-between
  #navbarSupportedContent.collapse.navbar-collapse.justify-content-end
    -# .form-inline

    - if user_signed_in?
      %ul.navbar-nav
        %li.nav-item
          = link_to "New Pin", new_pin_path, class: 'btn btn-primary'
        %li.nav-item
          = link_to "Account", edit_user_registration_path, class: 'btn btn-outline-primary'
        %li.nav-item
          = link_to "Sign Out", destroy_user_session_path, method: :delete, class: 'btn btn-danger'
    - else
      %ul.navbar-nav
        %li.nav-item= link_to "Sign Up", new_user_registration_path, class:'btn btn-primary'
        %li.nav-item= link_to "Log In", new_user_session_path, class: 'btn btn-success'

app/views/layouts/application.html.haml
!!!
%html
  %head
    %meta{:content => "text/html; charset=UTF-8", "http-equiv" => "Content-Type"}/
    %title PhotoBoard
    = csrf_meta_tags
    = stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload'
    = javascript_include_tag 'application', 'data-turbolinks-track': 'reload'

    %link{:crossorigin => "anonymous", :href => "https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0-alpha.6/css/bootstrap.min.css", :integrity => "sha384-rwoIResjU2yc3z8GV/NPeZWAv56rSmLldC3R/AZzGRnGxQQKnKkoFVhFQhNUwEyJ", :rel => "stylesheet"}/
    %script{:crossorigin => "anonymous", :integrity => "sha384-A7FZj7v+d/sdmMqp/nOQwliLvUsJfDHW+k9Omg/a/EheAdgtzNs3hpfag6Ed950n", :src => "https://code.jquery.com/jquery-3.1.1.slim.min.js"}
    %script{:crossorigin => "anonymous", :integrity => "sha384-DztdAPBWPRXSA/3eYEEUWrWCy7G5KFbe8fFjk5JAIxUYHKkDx6Qin1DkWx51bBrb", :src => "https://cdnjs.cloudflare.com/ajax/libs/tether/1.4.0/js/tether.min.js"}
    %script{:crossorigin => "anonymous", :integrity => "sha384-vBWWzlZJ8ea9aCX4pEW3rVHjgjt7zpkNpZk+02D9phzyeVkE+jo0ieGizqPLForn", :src => "https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0-alpha.6/js/bootstrap.min.js"}





  %body

    - flash.each do |name, msg|
      = content_tag :div, msg, class: "alert alert-info"

    = render 'layouts/nav'

    .container
      = yield

app/views/pins/_form.html.haml
= simple_form_for @pin, html: { multipart: true } do |f|
  - if @pin.errors.any?
    #errors
    %h2
      = pluralize(@pin.errors.count, "error" )
      prevented this Pin from saving
      %ul
        - @pin.errors.full_messages.each do |msg|
          %li= msg

  .form-group
    = f.input :image, input_html: { class: 'form-control'}

  .form-group
    = f.input :title, input_html: { class: 'form-control'}

  .form-group
    =f.input :description, input_html: { class: 'form-control'}

  = f.button :submit, class: 'btn btn-primary'

app/views/pins/edit.html.haml
%h1 Edit Pin
= image_tag @pin.image.url(:medium)
= render 'form'
= link_to "Cancel", pin_path, class: 'btn btn-primary'

app/views/pins/index.html.haml
-# .card
#pins.transitions-enabled
- @pins.each do |pin|
  .box.panel.panel-default
    = link_to (image_tag pin.image.url(:large)), pin
    .panel-body
      %h2= pin.title

  -# .box
  -#   .card
  -#     .card-header
  -#       %p Submitted by:
  -#       = pin.user.user_name
  -#     .card-img-top
  -#       = image_tag pin.image.url(:medium)
  -#     .card-block
  -#       %h2= link_to pin.title, pin

app/views/pins/new.html.haml
.col-md-6.col.md-offset-3
  = render 'form'

  = link_to 'Back', root_path, class: 'btn btn-outline-primary'

app/views/pins/show.html.haml
-# = image_tag @pin.image.url(:medium)
-# %h2= @pin.title
-# %p= @pin.description
-# %p Created by:
-# %p= @pin.user.user_name

/ HTML Code for Panel with Aqua Header
.panel
  .panel-heading
    %h2.panel-title= @pin.title
    %p= @pin.user.user_name
  .panel-body
    = image_tag @pin.image.url(:instagram)
  .panel-footer
    %p= @pin.description
/ End Aqua Panel

- if @pin.user.id == current_user.id
  .text-center.edit-links
    = link_to "Cancel", pins_path, class: 'btn btn-outline-secondary'
    |
    = link_to "Edit Pin", edit_pin_path(@pin), class: 'btn btn-primary'
    |
    = link_to "Delete", pin_path, method: :delete, data: { confirm: "Really?" }, class: 'btn btn-danger'
- else
  .text-center.edit-links
    = link_to "Back", pins_path


-# = link_to 'BACK', root_path, class: 'btn btn-primary'
-# = link_to 'EDIT', edit_pin_path, class: 'btn btn-outline-primary'
-# = link_to "DELETE", pin_path, method: :delete, data: { confirm: "Really?"}, class: 'btn btn-danger'